version: "3.7"
services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
        volumes:
            - ./postgresql/pgdata:/var/lib/postgresql/data
    app:
        build:
            # use env variables during docker-compose build 
            # https://stackoverflow.com/questions/52429984/docker-compose-build-environment-variable
            context: .
            args:
                - REACT_APP_BASEPATH_APP=${REACT_APP_BASEPATH_APP}
                - REACT_APP_BASEPATH_MANAGEMENT=${REACT_APP_BASEPATH_MANAGEMENT}
                - SOCKET_PATH=${SOCKET_PATH}
        container_name: app
        depends_on:
            - db
        environment:
            PGHOST: db
            PGPASSWORD: ${PGPASSWORD}
            PGUSER: ${PGUSER}
            WEATHER_API_KEY: ${WEATHER_API_KEY}
            WEATHER_LOCATION_LAT: ${WEATHER_LOCATION_LAT}
            WEATHER_LOCATION_LON: ${WEATHER_LOCATION_LON}
            REACT_APP_BASEPATH_APP: ${REACT_APP_BASEPATH_APP}
            REACT_APP_BASEPATH_MANAGEMENT: ${REACT_APP_BASEPATH_MANAGEMENT}
            SOCKET_PATH: ${SOCKET_PATH}
        ports:
            - '8910:8910'