version: "3.7"
services:
  db:
    restart: always
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
  app:
    restart: always
    build:
      # use env variables during docker-compose build 
      # https://stackoverflow.com/questions/52429984/docker-compose-build-environment-variable
      context: .
      args:
        - BASEPATH_APP=${BASEPATH_APP}
        - BASEPATH_MANAGEMENT=${BASEPATH_MANAGEMENT}
        - WEATHER_PROVIDER_URL=${WEATHER_PROVIDER_URL}
        - GROCERY_CART_URL=${GROCERY_CART_URL}
        - GROCERY_CART_TOKEN=${GROCERY_CART_TOKEN}
    container_name: app
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPASSWORD: postgres
      PGUSER: postgres
      WEATHER_PROVIDER_URL: ${WEATHER_PROVIDER_URL}
      REACT_APP_BASEPATH_APP: ${BASEPATH_APP}
      REACT_APP_BASEPATH_MANAGEMENT: ${BASEPATH_MANAGEMENT}
      GROCERY_CART_URL: ${GROCERY_CART_URL}
      GROCERY_CART_TOKEN: ${GROCERY_CART_TOKEN}
    ports:
      - '8910:8910'
