version: "3.7"
services:
  frontend_provider:
    restart: always
    build:
      # use env variables during docker-compose build 
      # https://stackoverflow.com/questions/52429984/docker-compose-build-environment-variable
      context: .
      args:
        - WEATHER_PROVIDER_URL=${WEATHER_PROVIDER_URL}
        - WEATHER_PROVIDER_TOKEN=${WEATHER_PROVIDER_TOKEN}
        - GROCERY_CART_URL=${GROCERY_CART_URL}
        - GROCERY_CART_TOKEN=${GROCERY_CART_TOKEN}
        - TASKS_URL=${TASKS_URL}
        - TASKS_TOKEN=${TASKS_TOKEN}
    container_name: frontend_provider
    environment:
      WEATHER_PROVIDER_URL: ${WEATHER_PROVIDER_URL}
      WEATHER_PROVIDER_TOKEN: ${WEATHER_PROVIDER_TOKEN}
      GROCERY_CART_URL: ${GROCERY_CART_URL}
      GROCERY_CART_TOKEN: ${GROCERY_CART_TOKEN}
      TASKS_URL: ${TASKS_URL}
      TASKS_TOKEN: ${TASKS_TOKEN}
    ports:
      - '8910:8910'
