# This is a basic workflow that is manually triggered

name: Build And Run Digital Information Administrator on local self hosted action listener

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [main] 
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_and_run:
    name: Build
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        clean: false
    
    - name: Build Dockerfiles
      run: sudo docker-compose build
      
    - name: Run Docker Images
      run: sudo docker-compose up -d
    
    - name: Send greeting
      run: echo "Hello You"
      
    - name: end
      run: echo "end"
